services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    privileged: true

  group-buy-market:
    image: group-buy-market:1.0
    container_name: group-buy-market
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=8091
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-change_me}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-group_buy_market}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_HIKARI_POOL_NAME=Retail_HikariCP
      - SPRING_RABBITMQ_ADDRESS=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER:-admin}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-change_me}
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
